/* config_main.c — interactive editor for MRCBBS.DAT (bridge BBS identity). */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <windows.h>

#define DAT_FILE "MRCBBS.DAT"
#define CONW     78   /* console width for word-wrap */

static HANDLE g_con = INVALID_HANDLE_VALUE;

/* Cache the stdout console handle. */
static void con_init(void) {
    g_con = GetStdHandle(STD_OUTPUT_HANDLE);
}

/* Set the console foreground color (0-15). */
static void con_color(int fg) {
    if (g_con == INVALID_HANDLE_VALUE) return;
    SetConsoleTextAttribute(g_con, (WORD)(fg & 0x0F));
}

/* Restore the default light-gray foreground. */
static void con_reset(void) { con_color(7); }

/* printf with a temporary foreground color. */
static void cprintf(int fg, const char *fmt, ...) {
    char buf[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    con_color(fg);
    fputs(buf, stdout);
    con_reset();
}

/* Strip trailing CR/LF/space in place. */
static void trim_crlf(char *s) {
    size_t n = strlen(s);
    while (n > 0 && (s[n-1] == '\r' || s[n-1] == '\n' || s[n-1] == ' '))
        s[--n] = 0;
}

/* Bounded string copy with guaranteed NUL termination. */
static void safe_copy_cfg(char *dst, size_t dstsz, const char *src) {
    if (!dst || dstsz == 0) return;
    if (!src) { dst[0] = 0; return; }
    strncpy(dst, src, dstsz - 1);
    dst[dstsz - 1] = 0;
}

/* Print a full-width horizontal rule. */
static void con_hr(int fg) {
    int i;
    con_color(fg);
    for (i = 0; i < CONW; i++) putchar('-');
    putchar('\n');
    con_reset();
}

/* Word-wrap text to console width and print with prefix on each line. */
static void print_note(int fg, const char *prefix, const char *text) {
    int plen = (int)strlen(prefix);
    int cols  = CONW - plen;
    const char *p = text;
    con_color(fg);
    while (*p) {
        const char *end = p + cols;
        const char *brk;
        if ((int)strlen(p) <= cols) {
            fputs(prefix, stdout);
            fputs(p, stdout);
            putchar('\n');
            break;
        }
        /* Walk back to last space within cols. */
        brk = end;
        while (brk > p && *brk != ' ') brk--;
        if (brk == p) brk = end;  /* no space found - hard break */
        fputs(prefix, stdout);
        fwrite(p, 1, (size_t)(brk - p), stdout);
        putchar('\n');
        p = brk;
        while (*p == ' ') p++;
    }
    con_reset();
}

typedef struct {
    char bbs_name[64];
    char bbs_pretty[64];
    char sysop[64];
    char description[128];
    char telnet[128];
    char ssh[128];
    char website[128];
    char server[128];       /* MRC relay hostname */
    int  port;              /* MRC relay port (default 5000) */
    int  show_motd;         /* 1 = auto-fetch MOTD once on connect */
} mrcbbs_cfg_t;

/* Default MRC relays shown in the server-selection menu. */
#define SERVER_NA "na-multi.relaychat.net"
#define SERVER_EU "eu-multi.relaychat.net"
#define SERVER_AU "au-multi.relaychat.net"

/* Zero an mrcbbs_cfg_t. */
static void cfg_clear(mrcbbs_cfg_t *c) { memset(c, 0, sizeof(*c)); }

/* Load MRCBBS.DAT into c; returns 1 on success, 0 if absent. */
static int cfg_load(mrcbbs_cfg_t *c) {
    FILE *fp;
    char line[512], *eq;
    cfg_clear(c);
    fp = fopen(DAT_FILE, "r");
    if (!fp) return 0;
    while (fgets(line, sizeof(line), fp)) {
        char *k, *v;
        trim_crlf(line);
        if (!line[0] || line[0] == '#') continue;
        eq = strchr(line, '=');
        if (!eq) continue;
        *eq = '\0';
        k = line; while (*k == ' ') ++k;
        v = eq + 1; while (*v == ' ') ++v;
        if      (strcmp(k, "bbs_name")    == 0) strncpy(c->bbs_name,    v, sizeof(c->bbs_name)-1);
        else if (strcmp(k, "bbs_pretty")  == 0) strncpy(c->bbs_pretty,  v, sizeof(c->bbs_pretty)-1);
        else if (strcmp(k, "sysop")       == 0) strncpy(c->sysop,       v, sizeof(c->sysop)-1);
        else if (strcmp(k, "description") == 0) strncpy(c->description, v, sizeof(c->description)-1);
        else if (strcmp(k, "telnet")      == 0) strncpy(c->telnet,      v, sizeof(c->telnet)-1);
        else if (strcmp(k, "ssh")         == 0) strncpy(c->ssh,         v, sizeof(c->ssh)-1);
        else if (strcmp(k, "website")     == 0) strncpy(c->website,     v, sizeof(c->website)-1);
        else if (strcmp(k, "server")      == 0) strncpy(c->server,      v, sizeof(c->server)-1);
        else if (strcmp(k, "port")        == 0) c->port      = atoi(v);
        else if (strcmp(k, "show_motd")   == 0) c->show_motd = (atoi(v) != 0);
    }
    fclose(fp);
    return 1;
}

/* Write c out to MRCBBS.DAT. */
static int cfg_save(const mrcbbs_cfg_t *c) {
    FILE *fp = fopen(DAT_FILE, "w");
    if (!fp) { fprintf(stderr, "ERROR: Cannot write %s\n", DAT_FILE); return 0; }
    fprintf(fp, "# MRC Bridge BBS Configuration\n");
    fprintf(fp, "# Generated by config.exe\n");
    fprintf(fp, "#\n");
    fprintf(fp, "# bbs_name    : Internal MRC identifier (underscores, no spaces)\n");
    fprintf(fp, "# bbs_pretty  : Display name shown in MRC listings\n");
    fprintf(fp, "# sysop       : SysOp handle used in BBSMETA\n");
    fprintf(fp, "# description : Short BBS description (INFO DSC) - plain text only\n");
    fprintf(fp, "# telnet      : host:port for telnet access (INFO TEL)\n");
    fprintf(fp, "# ssh         : host:port for SSH access (INFO SSH)\n");
    fprintf(fp, "# website     : website URL (INFO WEB)\n");
    fprintf(fp, "# server      : MRC relay hostname (NA/EU/AU or custom)\n");
    fprintf(fp, "# port        : MRC relay port (default 5000)\n");
    fprintf(fp, "# show_motd   : 1 = fetch MOTD on connect, 0 = skip\n");
    fprintf(fp, "\n");
    fprintf(fp, "bbs_name=%s\n",    c->bbs_name);
    fprintf(fp, "bbs_pretty=%s\n",  c->bbs_pretty);
    fprintf(fp, "sysop=%s\n",       c->sysop);
    fprintf(fp, "description=%s\n", c->description);
    fprintf(fp, "telnet=%s\n",      c->telnet);
    fprintf(fp, "ssh=%s\n",         c->ssh);
    fprintf(fp, "website=%s\n",     c->website);
    fprintf(fp, "server=%s\n",      c->server[0] ? c->server : SERVER_NA);
    fprintf(fp, "port=%d\n",        c->port > 0 ? c->port : 5000);
    fprintf(fp, "show_motd=%d\n",   c->show_motd ? 1 : 0);
    fclose(fp);
    return 1;
}

/* Derive an internal name from a display name (spaces -> underscores). */
static void auto_internal_name(const char *pretty, char *out, int outsz) {
    int i, j = 0;
    for (i = 0; pretty[i] && j < outsz - 1; ++i)
        out[j++] = (pretty[i] == ' ') ? '_' : pretty[i];
    out[j] = '\0';
}

/* Check required fields; prints an error and returns 0 on failure. */
static int validate(const mrcbbs_cfg_t *c) {
    if (!c->bbs_name[0])    { cprintf(12, "ERROR: BBS internal name is required.\n");  return 0; }
    if (!c->bbs_pretty[0])  { cprintf(12, "ERROR: BBS display name is required.\n");   return 0; }
    if (!c->sysop[0])       { cprintf(12, "ERROR: SysOp name is required.\n");         return 0; }
    if (!c->description[0]) { cprintf(12, "ERROR: BBS description is required.\n");    return 0; }
    if (!c->telnet[0])      { cprintf(12, "ERROR: Telnet address is required.\n");     return 0; }
    if (strchr(c->bbs_name, ' ')) {
        cprintf(12, "ERROR: BBS internal name must not contain spaces (use underscores).\n");
        return 0;
    }
    return 1;
}

/* Print a labeled field row. */
static void show_field(const char *label, const char *value) {
    cprintf(11, "  %-20s", label);
    cprintf(15, "%s\n", value[0] ? value : "(not set)");
}

/* Render the current configuration to the console. */
static void show_current(const mrcbbs_cfg_t *c) {
    putchar('\n');
    con_hr(8);
    cprintf(14, "  Current Configuration\n");
    con_hr(8);
    show_field("BBS Internal Name :", c->bbs_name);
    show_field("BBS Display Name  :", c->bbs_pretty);
    show_field("SysOp Handle      :", c->sysop);
    show_field("Description       :", c->description);
    show_field("Telnet Address    :", c->telnet);
    show_field("SSH Address       :", c->ssh[0] ? c->ssh : "(none)");
    show_field("Website           :", c->website[0] ? c->website : "(none)");
    {
        char sv[160];
        snprintf(sv, sizeof(sv), "%s:%d",
                 c->server[0] ? c->server : SERVER_NA,
                 c->port > 0 ? c->port : 5000);
        show_field("MRC Server        :", sv);
    }
    show_field("Show MOTD on conn :", c->show_motd ? "yes" : "no");
    con_hr(8);
    putchar('\n');
}

/* Interactive server-selection menu; updates c->server and c->port. */
static void prompt_server(mrcbbs_cfg_t *c) {
    char buf[160];
    cprintf(14, "\n  MRC Server\n");
    cprintf(8, "  Pick a relay (all plain TCP, port 5000):\n\n");
    cprintf(15, "    1");
    cprintf(7, ") North-America ");
    cprintf(14, "*");
    cprintf(7,  "  %s  (default)\n", SERVER_NA);
    cprintf(15, "    2");
    cprintf(7, ") Europe           %s\n", SERVER_EU);
    cprintf(15, "    3");
    cprintf(7, ") Australia        %s\n", SERVER_AU);
    cprintf(15, "    4");
    cprintf(7, ") Enter manually\n\n");
    if (c->server[0]) {
        cprintf(8, "  Current: %s:%d\n", c->server, c->port > 0 ? c->port : 5000);
    }
    cprintf(11, "  Choose [");
    cprintf(15, "1");
    cprintf(11, "/2/3/4, Enter=keep]: ");
    fflush(stdout);
    if (!fgets(buf, sizeof(buf), stdin)) return;
    trim_crlf(buf);
    if (buf[0] == '\0') {
        if (!c->server[0]) {
            safe_copy_cfg(c->server, sizeof(c->server), SERVER_NA);
            c->port = 5000;
        }
        return;
    }
    if (buf[0] == '1') {
        safe_copy_cfg(c->server, sizeof(c->server), SERVER_NA);
        c->port = 5000;
    } else if (buf[0] == '2') {
        safe_copy_cfg(c->server, sizeof(c->server), SERVER_EU);
        c->port = 5000;
    } else if (buf[0] == '3') {
        safe_copy_cfg(c->server, sizeof(c->server), SERVER_AU);
        c->port = 5000;
    } else if (buf[0] == '4') {
        char host[160];
        cprintf(11, "  Hostname (no port): ");
        fflush(stdout);
        if (!fgets(host, sizeof(host), stdin)) return;
        trim_crlf(host);
        if (host[0])
            safe_copy_cfg(c->server, sizeof(c->server), host);
        cprintf(11, "  Port [5000]: ");
        fflush(stdout);
        if (!fgets(host, sizeof(host), stdin)) return;
        trim_crlf(host);
        c->port = host[0] ? atoi(host) : 5000;
        if (c->port <= 0) c->port = 5000;
    }
}

/* Prompt for a single field; Enter keeps the current value. */
static void prompt_field(const char *label, char *buf, int bufsz, const char *cur) {
    char tmp[512];
    cprintf(11, "  %s", label);
    if (cur && *cur) {
        cprintf(8, " [");
        cprintf(7, "%s", cur);
        cprintf(8, "]");
    }
    cprintf(7, ": ");
    fflush(stdout);
    if (!fgets(tmp, sizeof(tmp), stdin)) return;
    trim_crlf(tmp);
    if (tmp[0] != '\0') {
        memcpy(buf, tmp, (size_t)(bufsz - 1));
        buf[bufsz - 1] = '\0';
    } else if (cur && cur[0]) {
        memcpy(buf, cur, (size_t)(bufsz - 1));
        buf[bufsz - 1] = '\0';
    }
}

/* Entry point — walks the user through every section and saves MRCBBS.DAT. */
int main(void) {
    mrcbbs_cfg_t cfg;
    int existing;
    char yn[8], auto_name[64];

    con_init();
    SetConsoleTitle("MRC Bridge Configuration");

    /* Banner */
    con_hr(14);
    cprintf(14, "  ANET MRC Bridge  -  BBS Configuration\n");
    cprintf(8,  "  Writes: %s\n", DAT_FILE);
    con_hr(14);

    existing = cfg_load(&cfg);

    if (existing) {
        cprintf(10, "\n  Existing configuration loaded.\n");
        cprintf(7,  "  Press ENTER on any field to keep the current value.\n");
        show_current(&cfg);
    } else {
        cprintf(14, "\n  No existing configuration found.  Starting fresh.\n\n");
    }

    /* ------------------------------------------------------------------ */
    /* Section 1: BBS Identity                                             */
    /* ------------------------------------------------------------------ */
    con_hr(8);
    cprintf(14, "  SECTION 1 - BBS Identity\n");
    con_hr(8);
    print_note(8, "  ",
        "These fields identify your BBS on the MRC network.  "
        "They appear in /whoon, INFO listings, and the BBSMETA handshake.");
    putchar('\n');

    /* BBS Display Name */
    print_note(8, "  ", "The display name may contain spaces.  Example: A-Net Online");
    prompt_field("BBS Display Name", cfg.bbs_pretty, sizeof(cfg.bbs_pretty), cfg.bbs_pretty);

    /* BBS Internal Name */
    if (!existing || !cfg.bbs_name[0]) {
        auto_internal_name(cfg.bbs_pretty, auto_name, sizeof(auto_name));
        memcpy(cfg.bbs_name, auto_name, sizeof(cfg.bbs_name) - 1);
        cfg.bbs_name[sizeof(cfg.bbs_name) - 1] = '\0';
    }
    print_note(8, "  ", "Internal name: single word, underscores instead of spaces.  "
                        "Auto-suggested from display name above.");
    prompt_field("BBS Internal Name", cfg.bbs_name, sizeof(cfg.bbs_name), cfg.bbs_name);
    /* Enforce no spaces */
    {
        char *p;
        while ((p = strchr(cfg.bbs_name, ' ')) != NULL) *p = '_';
    }

    /* SysOp */
    print_note(8, "  ", "Your MRC handle as SysOp.  Sent in the BBSMETA packet on connect.");
    prompt_field("SysOp Handle      ", cfg.sysop, sizeof(cfg.sysop), cfg.sysop);

    /* ------------------------------------------------------------------ */
    /* Section 2: BBS Description                                          */
    /* ------------------------------------------------------------------ */
    putchar('\n');
    con_hr(8);
    cprintf(14, "  SECTION 2 - BBS Description\n");
    con_hr(8);
    print_note(8, "  ",
        "Shown when another MRC user types INFO N.  Plain text only - "
        "pipe color codes (|NN) are NOT supported here and will appear as "
        "literal characters in listings.  Max 120 characters.");
    putchar('\n');
    prompt_field("BBS Description   ", cfg.description, sizeof(cfg.description), cfg.description);

    /* ------------------------------------------------------------------ */
    /* Section 3: Connection Info                                          */
    /* ------------------------------------------------------------------ */
    putchar('\n');
    con_hr(8);
    cprintf(14, "  SECTION 3 - Connection Info\n");
    con_hr(8);
    print_note(8, "  ",
        "Telnet and SSH addresses are sent as INFOTEL / INFOSSH packets on "
        "connect and are shown in INFO listings.  Format: hostname:port.  "
        "SSH and Website are optional - press ENTER to leave blank.");
    putchar('\n');

    print_note(8, "  ", "Example: bbs.example.com:23");
    prompt_field("Telnet Address    ", cfg.telnet, sizeof(cfg.telnet), cfg.telnet);

    print_note(8, "  ", "Example: bbs.example.com:22  (leave blank if N/A)");
    prompt_field("SSH Address       ", cfg.ssh, sizeof(cfg.ssh), cfg.ssh);

    print_note(8, "  ", "Example: https://bbs.example.com  (leave blank if N/A)");
    prompt_field("Website URL       ", cfg.website, sizeof(cfg.website), cfg.website);

    /* ------------------------------------------------------------------ */
    /* Section 4: MRC Server                                               */
    /* ------------------------------------------------------------------ */
    putchar('\n');
    con_hr(8);
    cprintf(14, "  SECTION 4 - MRC Server\n");
    con_hr(8);
    print_note(8, "  ",
        "Which MRC relay to connect to.  The North-America relay is the "
        "default and has the most bridges.  Pick a regional relay for lower "
        "latency, or 4 to enter a custom host/port.");
    prompt_server(&cfg);

    /* ------------------------------------------------------------------ */
    /* Section 5: Display Flags                                            */
    /* ------------------------------------------------------------------ */
    putchar('\n');
    con_hr(8);
    cprintf(14, "  SECTION 5 - Display Flags\n");
    con_hr(8);
    print_note(8, "  ",
        "Optional on-connect behaviours.  Enable show-MOTD if you'd like "
        "every user to see the server's message of the day right after "
        "joining the lobby - disabled by default to keep connect snappy.");
    putchar('\n');
    {
        char buf[16];
        cprintf(11, "  Show MOTD on connect? ");
        cprintf(8,  "[");
        cprintf(15, cfg.show_motd ? "Y" : "y");
        cprintf(8,  "/");
        cprintf(15, cfg.show_motd ? "n" : "N");
        cprintf(8,  "]: ");
        fflush(stdout);
        if (fgets(buf, sizeof(buf), stdin)) {
            trim_crlf(buf);
            if (buf[0] == 'y' || buf[0] == 'Y') cfg.show_motd = 1;
            else if (buf[0] == 'n' || buf[0] == 'N') cfg.show_motd = 0;
            /* Empty = keep existing */
        }
    }

    /* ------------------------------------------------------------------ */
    /* Review and save                                                     */
    /* ------------------------------------------------------------------ */
    show_current(&cfg);

    if (!validate(&cfg)) {
        cprintf(12, "\n  Configuration NOT saved due to errors.  Please re-run config.exe.\n");
        cprintf(7, "\n  Press Enter to exit...\n");
        fgets(yn, sizeof(yn), stdin);
        return 1;
    }

    cprintf(11, "  Save this configuration? ");
    cprintf(8, "[");
    cprintf(15, "Y");
    cprintf(8, "/n]: ");
    fflush(stdout);
    if (!fgets(yn, sizeof(yn), stdin)) yn[0] = 'y';
    if (yn[0] == 'n' || yn[0] == 'N') {
        cprintf(14, "  Configuration NOT saved.\n");
        return 1;
    }

    if (!cfg_save(&cfg)) return 1;

    putchar('\n');
    cprintf(10, "  Configuration saved to %s\n", DAT_FILE);
    cprintf(7,  "  You can now run anetmrc_bridge.exe.\n\n");
    cprintf(8,  "  Press Enter to exit...\n");
    fgets(yn, sizeof(yn), stdin);
    return 0;
}
